DROP TABLE IF EXISTS `[DATABASE_PREFIX]status`;

CREATE TABLE `[DATABASE_PREFIX]status` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `service` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `port` varchar(255) DEFAULT NULL,
  `status` enum('ONLINE','OFFLINE') DEFAULT 'OFFLINE',
  `time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=1;
