name: Create installable ZIP-Packages of Modules
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Build Module-Packages
      CI_COMMIT_AUTHOR: fruithost | Modules Builder
    steps:
    - uses: actions/checkout@v3

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: '22' 
    - name: Change Directory
      run: cd ./.builder/
    - name: Node Install
      run: npm ci
    - name: Node Build
      run: node ./build.js

    # Commit and push all changed files.
    - name: Commit changes
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "fruithost@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push