name: Create installable ZIP-Packages of Modules
on: [workflow_dispatch]
jobs:
  test:
    name: Start
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [22]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    
    - name: npm install, build and test
      run: |
        cd ./.builder/
        npm install
        node ./build.js
